{
 "title": "HLF-Connector",
 "tags": [
  "spring",
  "http"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Healthy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up{}" }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-process_start_time_seconds{}"
    }
   ]
  },
  {
   "title": "Error 5xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{status=~\"5..\" })"
    }
   ]
  },
  {
   "title": "Total Transactions (Kafka + HTTP)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(http_server_requests_seconds_count{uri=~\".*invoke_transaction|.*write_transaction|.*init_transaction|.*query_transaction\"}) or vector(0))+ (sum(kafka_messages_processed_total{}) or vector(0) )",
     "legendFormat": "Transaction Received"
    },
    {
     "expr": "(sum(http_server_requests_seconds_count{uri=~\".*invoke_transaction|.*write_transaction|.*init_transaction|.*query_transaction\",status!~\"5..|4..\"})   or\n  vector(0) ) + (sum(kafka_messages_processed_total{})  or\n  vector(0) ) - (sum(kafka_messages_failed_messages_total{})  or\n  vector(0) )",
     "legendFormat": "Successful Transactions"
    },
    {
     "expr": "(sum(http_server_requests_seconds_count{uri=~\".*invoke_transaction|.*write_transaction|.*init_transaction|.*query_transaction\", status=~\"5..|4..\"}) or vector(0) ) + (sum(kafka_messages_failed_messages_total{}) or vector(0))",
     "legendFormat": "Failed Transactions"
    }
   ]
  },
  {
   "title": "Total Async Transaction (Kafka)",
   "type": "bargauge",
   "description": "Total number of transaction processed from Kafka",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_messages_processed_total{}",
     "legendFormat": "Transactions Received"
    },
    {
     "expr": "kafka_messages_processed_total{} - kafka_messages_failed_messages_total{}",
     "legendFormat": "Successul Transaction"
    },
    {
     "expr": "kafka_messages_failed_messages_total{}",
     "legendFormat": "Failed Transaction"
    }
   ]
  },
  {
   "title": "Total Transactions (HTTP)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(http_server_requests_seconds_count{uri=~\".*invoke_transaction|.*write_transaction|.*init_transaction|.*query_transaction\"}) or vector(0))",
     "legendFormat": "Transaction Received"
    },
    {
     "expr": "(sum(http_server_requests_seconds_count{uri=~\".*invoke_transaction|.*write_transaction|.*init_transaction|.*query_transaction\",status!~\"5..|4..\"})   or\n  vector(0) )",
     "legendFormat": "Successful Transactions"
    },
    {
     "expr": "(sum(http_server_requests_seconds_count{uri=~\".*invoke_transaction|.*write_transaction|.*init_transaction|.*query_transaction\", status=~\"5..|4..\"}) or vector(0) )",
     "legendFormat": "Failed Transactions"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(\n    sum by (method, uri, exception, status) (\n        increase(\n            http_server_requests_seconds_count{status=~\"5..|4..\" , }[$__range]\n        )\n    ) > 0, \n    'uri', \n    '$1/*$2', \n    'uri', \n    '(.*)\\\\/\\\\{.+\\\\}(.*)'\n)"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by(exception) (increase(http_server_requests_seconds_count{exception!=\"None\" , }[$__range]))) > 0"
    }
   ]
  },
  {
   "title": "Top 10 Longest Requests",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, max (max_over_time(http_server_requests_seconds_max{}[$__range])) by(uri, outcome, method))"
    },
    {
     "expr": "sum (increase(http_server_requests_seconds_count{}[$__range])) by(uri, outcome, method)"
    },
    {
     "expr": "sum by(uri, outcome, method) (\n    increase(http_server_requests_seconds_sum{}[$__range])\n)\n/ \nsum by(uri, outcome, method) (\n    increase(http_server_requests_seconds_count{}[$__range])\n)"
    }
   ]
  },
  {
   "title": "Transaction Respone time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_sum{uri=~\".*invoke_transaction|.*write_transaction\" , }[$__rate_interval])) / sum by (uri) (rate(http_server_requests_seconds_count{uri=~\".*invoke_transaction|.*write_transaction\" , }[$__rate_interval]))",
     "legendFormat": "Transaction Invoke"
    }
   ]
  },
  {
   "title": "Query Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_sum{ uri=~\".*query_transaction\", }[$__rate_interval])) / sum by (uri) (rate(http_server_requests_seconds_count{uri=~\".*query_transaction\" , }[$__rate_interval]))",
     "legendFormat": "Query"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(http_server_requests_seconds_count{}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "RPS by URI",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 7, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(uri) (irate(http_server_requests_seconds_count{}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status) (irate(http_server_requests_seconds_count{}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(instance) (increase(http_server_requests_seconds_sum{}[$__rate_interval]))\n / \n(sum by(instance) (increase(http_server_requests_seconds_count{}[$__rate_interval])) != 0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Avg Latency (by outcome)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(outcome) (increase(http_server_requests_seconds_sum{}[$__rate_interval]))\n / \n (sum by(outcome) (increase(http_server_requests_seconds_count{}[$__rate_interval])) != 0)",
     "legendFormat": "{{outcome}}"
    }
   ]
  }
 ]
}