name: Pull Request CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: "actions/checkout@v2"
      - name: Setup JDK 8
        uses: "actions/setup-java@v2"
        with:
          java-version: '8'
          distribution: 'adopt-openj9'
      - name: Run tests
        run: mvn -B clean verify
      - name: Run build
        run: mvn -B package -DskipTests=true
