name: Merge Build and Sanity

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: "actions/checkout@v2"
      - name: Setup JDK 11
        uses: "actions/setup-java@v2"
        with:
          java-version: '11'
          distribution: 'adopt-openj9'
      - name: Run tests and lints
        run: mvn -B clean verify
      - name: Run build
        run: mvn -B clean package -DskipTests=true
