name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: "actions/checkout@v2"
      - name: Setup JDK 8
        uses: "actions/setup-java@v2"
        with:
          java-version: '8'
          distribution: 'adopt-openj9'
      - name: Run tests and lints
        run: mvn -B clean verify
      - name: Run build
        run: mvn -B clean package -DskipTests=true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: $GITHUB_ACTOR
          password: "${{ secrets.GITHUB_TOKEN }}"
      - name: Generate a container image
        run: |
          version=$(mvn -q \
              -Dexec.executable=echo \
              -Dexec.args='${project.version}' \
              --non-recursive \
              exec:exec)
          docker build . -t ghcr.io/${USERNAME_OR_ORG}/hlf-connector:${version}
          docker push ghcr.io/${USERNAME_OR_ORG}/hlf-connector:${version}
        shell: bash
        env:
          USERNAME_OR_ORG: "${{ github.repository_owner }}"
